### ISSUE TITLE
This package is not compatible with python3.9

### ISSUE THREAD

**Issue by amosbaker** [sassoftware/python-swat#113]
Same machine, same user, python compiled from source for 3.7 and 3.9 in the same way shows that this package does not work with python3.9 

Upon inspection of the install package it becomes apparent it's not installing any of the binary components.

```
[root@server]# pwd
./lib/python3.9/site-packages/swat/lib/linux
[root@server]# ll
total 4
-rw-rw-r--. 1 root root 657 Feb 10  2020 __init__.py
drwxrwxr-x. 2 root root  37 Mar  5 14:38 __pycache__
```

Attempting to connect results in:
```
Python 3.9.2 (default, Mar  5 2021, 14:33:48)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import swat
>>> conn = swat.CAS('myurl', username='myuser', password='mypass')
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PUT is not allowed for the URL /cas/sessions.</p>
</body></html>

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/swat/cas/rest/connection.py", line 332, in __init__
    out = json.loads(txt, strict=False)
  File "/usr/local/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/swat/cas/connection.py", line 301, in __init__
    self._sw_connection = rest.REST_CASConnection(*params)
  File "/usr/local/lib/python3.9/site-packages/swat/cas/rest/connection.py", line 359, in __init__
    raise SWATError(str(exc))
swat.exceptions.SWATError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kesmit13** [comment]
At the moment, the Python 3.9 extensions haven't been released. However, it appears as though you are using the REST interface so that shouldn't matter. You say you compiled from source. Do you mean you used the Github source? I think what may be happening here is that you are getting an old version of SWAT since there aren't Python 3.9 packages out yet. You may want to check your SWAT version: `print(swat.__version__)`.

**Comment by kesmit13** [comment]
v1.9.1 now contains the Python 3.9 extension.
