### ISSUE TITLE
Error while establishing connection with SWAT and CAS

### ISSUE THREAD

**Issue by AmeerFaisalAdanan** [sassoftware/python-swat#15]
I was having an error message stated that "The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative.". Im running on windows 10 with python 3.6.2 and swat version of 1.3.0 installed. Im new to this SAS platform so i have a little to no knowledge on this error. Based on the error, it state that i need to install an extension for the binary protocol. Is there any library on python that  i need to install (beside pandas) that im missing? Below is the error im having. Thanks.

>>> conn = swat.CAS(host, port, username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ameer Faisal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\swat-1.3.0-py3.6.egg\swat\cas\connection.py", line 254, in __init__
    self._sw_error = clib.SW_CASError(a2n(soptions))
  File "C:\Users\Ameer Faisal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\swat-1.3.0-py3.6.egg\swat\clib.py", line 120, in SW_CASError
    _import_pyswat()
  File "C:\Users\Ameer Faisal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\swat-1.3.0-py3.6.egg\swat\clib.py", line 65, in _import_pyswat
    raise ValueError('The extensions for the binary protocol have not been '
ValueError: The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative.

**Comment by fl0r3k** [comment]
Binary protocol is avaialable for linux platform. For Windows you can use REST.
conn = swat.CAS(host, port=8777, username, password, protocol='http').
