### ISSUE TITLE
Unable to connect -  Server returned %hs

### ISSUE THREAD

**Issue by thobianchi** [sassoftware/python-swat#35]
Connecting via REST with:
```
import swat
conn = swat.CAS("https://hostname:8777", username='user', password='pass')
```
I get this error:
```
Traceback (most recent call last):
  File "prova.py", line 5, in <module>
    conn = swat.CAS("https://***:8777", username='***', password='***')
  File "/opt/home/sasinst/viya-utils/swat/venv/lib/python2.7/site-packages/swat/cas/connection.py", line 300, in __init__
    self._sw_connection = rest.REST_CASConnection(*params)
  File "/opt/home/sasinst/viya-utils/swat/venv/lib/python2.7/site-packages/swat/cas/rest/connection.py", line 324, in __init__
    raise SWATError(str(exc))
swat.exceptions.SWATError: Could not connect to CAS server. (Connection failed. Server returned: %hs)
```
> User, password, host hidden

Can you help me please to debug this error?

**Comment by thobianchi** [comment]
I found further details in `[...]/viya/config/var/log/cas/default/cas_[...].log`:
```
2019-01-18T11:04:18,815 ERROR [00409858] *** local MAIN NoUser  [tkcls.c:194] - No user entry for uid 1862347.
2019-01-18T11:04:18,815 ERROR [00409858] *** local MAIN NoUser  [casutil.c:1005] - An unexpected return code 0xffffffff resulting in launch status -1 was detected while creating a new session in a call to CLSLaunch in file /sas/day/mva-vb015/tkcas/src/casutil.c line 1005.
2019-01-18T11:04:18,815 ERROR [00409858] *** local MAIN NoUser  [casgeneral.c:4509] - Failed to launch session controller.
2019-01-18T11:04:18,815 INFO  [00409858] *** local MAIN NoUser  [tkcsesinst.c:810] - Destroying session 954015a8-d2d5-4e4b-8e73-4e7d593b7868.
2019-01-18T11:04:18,821 ERROR [00409855] *** local MAIN NoUser  [httppkg.c:4598] - createSessionConnection: Could not connect to CAS server.Connection failed. Server returned: %hs
```
It seems a PAM related authentication error.

In `/var/log/secure`:
Jan 18 11:11:39 *** identsvcs[23719]: pam_unix(cas:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost= user=ee45759

**Comment by kesmit13** [comment]
I spoke with a colleague of mine who gave me this suggestion:

Typically this means that this is an MPP deployment and the user’s POSIX attributes do not match across the grid. Before I launch a session or worker process, I look the user’s uid up to get their password entry data structure (for home directory, etc). The Linux box returned NULL for that structure, so POSIX uid 1862347 does not exist as far as this linux system is concerned. The uid was obtained on the controller node using their username and password and passed to the worker nodes for launch. I will not launch a process on a node that differs in uid and primary gid from the main controller.

**Comment by thobianchi** [comment]
We have a single machine full deployment.
Once I solved the issue with PAM and restarted the CAS Server, I was able to connect.
Error: `"Server returned: %hs"` IMO should be more specific since from this I was not able to identify a login issue until I opened cas server logs.
