### ISSUE TITLE
Not compatible with latest Pandas version

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/python-swat#64]
Pandas v1.0.0 break swat:

```
>>> swat.CAS(hostname, port, username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/swat/cas/connection.py", line 348, in __init__
    _apptag='UI').items():
  File "/usr/local/lib/python3.6/site-packages/swat/cas/connection.py", line 1699, in retrieve
    responsefunc=responsefunc, resultfunc=resultfunc)
  File "/usr/local/lib/python3.6/site-packages/swat/cas/connection.py", line 1777, in _get_results
    for key, value in response:
  File "/usr/local/lib/python3.6/site-packages/swat/cas/response.py", line 333, in __iter__
    yield key, cas2py(_sw_result, self.soptions, connection=self._connection)
  File "/usr/local/lib/python3.6/site-packages/swat/cas/transformers.py", line 484, in cas2py
    casdt.cas2python_date, casdt.cas2python_time)
  File "/usr/local/lib/python3.6/site-packages/swat/cas/transformers.py", line 382, in ctb2tabular
    bygroup_collision_suffix=optbycolsfx)
  File "/usr/local/lib/python3.6/site-packages/swat/dataframe.py", line 828, in reshape_bygroups
    dframe = self[self.columns]
  File "/usr/local/lib/python3.6/site-packages/swat/dataframe.py", line 499, in __getitem__
    result = super(SASDataFrame, self).__getitem__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2812, in __getitem__
    data = self._take_with_is_copy(indexer, axis=1)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3408, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3396, in take
    return self._constructor(new_data).__finalize__(self)
  File "/usr/local/lib/python3.6/site-packages/swat/dataframe.py", line 418, in __init__
    self.attrs = attrs
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5286, in __setattr__
    return object.__setattr__(self, name, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 253, in attrs
    self._attrs = dict(value)
TypeError: 'NoneType' object is not iterable
>>> swat.__version__
'1.6.0'
>>> pandas.__version__
'1.0.0'
```

**Comment by frayos** [comment]
Indeed confirmed in Track : 7613000072

Workaround, remove Pandas, reinstall with : 
pip install "pandas==0.25.3"

**Comment by kesmit13** [comment]
There is an experimental feature in pandas 1.0.0 that collides with a feature of SASDataFrames.  Luckily, they are trying to implement the same behavior.  The SWAT code needs to be updated to still work with pre-1.0.0 pandas DataFrames, but use the existing feature in pandas >= 1.0.0.

**Comment by kesmit13** [comment]
SWAT v1.6.1 can now be used with pandas v1.0.0
