### ISSUE TITLE
How to get kerberos SSO working with tenant HTTPS in multi-tenant environment.

### ISSUE THREAD

**Issue by agdrorije** [sassoftware/python-swat#98]
I'm trying to get single sign on to work for my tenant python SWAT connections. For the binary connection this works fine, but for the HTTPS connection it fails. 

The tenant that I try to connect is running on _mycascontroller.hostname.nl_ with tenant ID _mytenant_. The binary port used is 32466 and the HTTPS port: 32467. 

I can logon using username='_mysername_' and password='_mypassword_' in the connect string. That works fine. 

Python code that I use:
```
import swat
import os
os.environ['CAS_CLIENT_SSL_CA_LIST'] = '/etc/pki/tls/certs/ca-bundle.trust.crt'

# mytenant Binary CAS port = OK with SSO
conn = swat.CAS('mycascontroller.hostname.nl', '32466',protocol='cas')
out = conn.serverstatus()

# mytenant HTTPS CAS port = NOK with SSO
conn = swat.CAS('mycascontroller.hostname.nl', '32467', protocol='https')
out = conn.serverstatus()
```
Output:
```
(py36env) [myuserid@linuxhost ~]$ python sas.py
# Binary:
NOTE: Grid node action status report: 4 nodes, 8 total actions executed.

# Rest:
Traceback (most recent call last):
  File "/home/myuserid/py36env/lib/python3.6/site-packages/swat/cas/rest/connection.py", line 341, in __init__
    raise SWATError(out['error'])
swat.exceptions.SWATError: HTTP/1.1 401 Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sas.py", line 21, in <module>
    conn = swat.CAS('mycascontroller.hostname.nl', '32467', protocol='https')
  File "/home/myuserid/py36env/lib/python3.6/site-packages/swat/cas/connection.py", line 301, in __init__
    self._sw_connection = rest.REST_CASConnection(*params)
  File "/home/myuserid/py36env/lib/python3.6/site-packages/swat/cas/rest/connection.py", line 359, in __init__
    raise SWATError(str(exc))
swat.exceptions.SWATError: HTTP/1.1 401 Unauthorized
```
CAS tenant controller log:
```
# Binary SSO:
2020-09-15T12:16:01,892 INFO  [00000030] MAIN NoUser MAIN [tkcalsident.c:335] - Obtained default authentication domain value of 'DefaultAuth'.
2020-09-15T12:16:01,935 INFO  [00000030] MAIN NoUser MAIN [tkcalsident.c:424] - New client connection accepted on port 32466. Client IP address and port are [CLIEN_IP_ADDRESS]:47358. TLS is required.
2020-09-15T12:16:01,935 INFO  [00000030] MAIN NoUser MAIN [tkcalsident.c:439] - Client version long is 'V.03.05M0P11062019'.
2020-09-15T12:16:01,938 INFO  [00000030] MAIN NoUser MAIN [tkidentgss.c:976] - User myuserid@MYDOMAIN.NL has authenticated using kerberos.
2020-09-15T12:16:01,969 INFO  [00000030] MAIN NoUser MAIN [tkident.c:1323] - User myuserid successfully authenticated using the Kerberos authentication provider.
2020-09-15T12:16:02,676 INFO  [00000030] MAIN NoUser MAIN [tkident.c:1323] - User myuserid successfully authenticated using the OAuth authentication provider.
2020-09-15T12:16:02,677 INFO  [00000030] MAIN NoUser MAIN [tkcsesinst.c:748] - Successfully created session 0f562f84-16e3-ea40-b2b2-561b3d95e845.
2020-09-15T12:16:02,692 INFO  [00000030] MAIN myuserid 1 [casgeneral.c:4824] - Launched session controller. Process ID is 14189.
2020-09-15T12:16:02,723 INFO  [00000007] 14189 myuserid MAIN [cas.c:2310] - Starting Cloud Analytic Services driver, host=mycascontroller.hostname.nl, id=0, role=session controller.
2020-09-15T12:16:02,724 INFO  [00000007] 14189 myuserid MAIN [tkcsesinst.c:748] - Successfully created session 0f562f84-16e3-ea40-b2b2-561b3d95e845.
2020-09-15T12:16:02,765 INFO  [00000007] 14189 myuserid 1 [tkhttpserver.c:1353] - Starting HTTP server 'mycascontroller.hostname.nl', minPort=0 maxPort=0
2020-09-15T12:16:02,765 INFO  [00000007] 14189 myuserid 1 [tkhttpserver.c:1438] - HTTP Server 'mycascontroller.hostname.nl' listening on port 38426.
2020-09-15T12:16:02,789 INFO  [00000007] 14189 myuserid 1 [cashttp.c:1936] - HTTP server is authenticating connections.
2020-09-15T12:16:02,790 INFO  [00000007] 14189 myuserid 1 [cashttp.c:1983] - HTTP server listening on HTTPS port 38426.
2020-09-15T12:16:02,902 INFO  [00000030] MAIN myuserid 1 [tkperm.c:21095] - User myuserid added the caslib CASUSER(myuserid) and is granted all permissions on it.
2020-09-15T12:16:02,903 INFO  [00000030] MAIN myuserid 1 [tkperm.c:21095] - User myuserid added the caslib CASUSERHDFS(myuserid) and is granted all permissions on it.
2020-09-15T12:16:02,919 INFO  [00000007] 14189 myuserid 1 [tkidentgss.c:2075] - Kerberos ticket in cache /tmp/tkt9GQILZ will be renewed on Tue Sep 15 21:07:07 2020.
2020-09-15T12:16:03,060 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4448] - ++ action sessionProp.setFmtSearch / fmtLibNames={'SASSuppliedFormats'};
2020-09-15T12:16:03,073 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] -  -- 'sessionProp.setFmtSearch' SUCCESSFUL.
2020-09-15T12:16:03,095 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action builtins.queryActionSet / actionSet='builtins.help', _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,098 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'builtins.queryActionSet' SUCCESSFUL.
2020-09-15T12:16:03,112 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action builtins.queryName / name='builtins.help', _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,114 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'builtins.queryName' SUCCESSFUL.
2020-09-15T12:16:03,126 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action builtins.reflect / actionSet='builtins', showHidden=true, _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,131 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'builtins.reflect' SUCCESSFUL.
2020-09-15T12:16:03,177 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action builtins.help / showHidden=true, _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,184 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'builtins.help' SUCCESSFUL.
2020-09-15T12:16:03,254 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action session.sessionName / name='py-session-1', _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,263 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'session.sessionName' SUCCESSFUL.
2020-09-15T12:16:03,282 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:4441] - A[UI]: ++ action builtins.serverStatus / _apptag='UI', _messageLevel='error';
2020-09-15T12:16:03,288 INFO  [00000007] 14189 myuserid 1 [tkcasalic.c:466] - Opening license file '/opt/sas/mytenant/config/etc/cas/default/sas_license.txt'.
2020-09-15T12:16:03,296 INFO  [00000007] 14189 myuserid 1 [tkcasaimp.c:6404] - A[UI]:  -- 'builtins.serverStatus' SUCCESSFUL.

# HTTPS: SSO
2020-09-15T12:16:03,651 ERROR [00000032] MAIN NoUser MAIN [tkmtrbMethods.c:2048] - SubmitRequestWithFiles: uri='https://mytenant.viyaproxy.hostname.nl:443/SASLogon/oauth/token', correlator='X-SAS-Correlator: 5EEEC6A3-83EC-1E44-8879-55CE92029E99;'.
2020-09-15T12:16:03,651 ERROR [00000032] MAIN NoUser MAIN [tkmtrbMethods.c:2051] - SubmitRequestWithFiles: status=8dbff992 httpStatus=401 'Unauthorized'.
2020-09-15T12:16:03,652 ERROR [00000032] MAIN NoUser MAIN [tkmtrbMethods.c:2076] - Username or password is invalid.
2020-09-15T12:16:03,652 ERROR [00000032] MAIN NoUser MAIN [tkmtrbAuth.c:1329] - Username or password is invalid.
2020-09-15T12:16:03,652 ERROR [00000032] MAIN NoUser MAIN [tkidentmid.c:717] - User 'None' failed mid-tier authentication.
2020-09-15T12:16:03,652 ERROR [00000032] MAIN NoUser MAIN [tkidentmid.c:721] - Access denied.
```
How can I get HTTPS SSO to work with Python SWAT?

**Comment by kesmit13** [comment]
At this time the CAS HTTP(S) server does not support Kerberos authentication.  It has only been implemented in the binary interface.

**Comment by agdrorije** [comment]
Thanks for the quick reply!

We will document that SWAT is only available on binary interface.

**Comment by kesmit13** [comment]
I'll make sure to notify the CAS server team there is a desire to have Kerberos over HTTP(S) in CAS so that it can be evaluated for future development.

**Comment by agdrorije** [comment]
That would be a nice add-on. In our environment the user doesn't know the password, so the only way to connect is with SSO.
